# configuration.yaml

data:
  pkl_name: './data_pkl-100ms.pkl'  # data_pkl.pkl OR data_pkl-100ms.pkl OR data_pkl-50ms.pkl
  val_samples: ['02', '07']
  test_samples: ['12', '13', '15', '28', '31']

model:
  name: "GRU1"  # LSTM1 or GRU1
  num_layers: None
  seq_length_s: 1
  samp_interval_s: 0.1  # 0.2 OR 0.1 OR 0.05
  predict_next_t: 1  # horizon of predicting the next {}th time sample (y)
  input_dim: 54
  hidden_dim1: 32
  hidden_dim2: 2
  #hidden_dim3: 0
  dropout_prob: 0.1

optimizer:
  name: "RMSprop"
  lr: 0.0001
  lr_step_size: 10
  gamma: 0.1

training:
  batch_size: 48
  epochs: 50
  early_stop_patience: 5
  saved_dir: "./checkpoints"
  saved_best_model: "-"
  is_only_last_timestep: false
  custom_weighted_loss: "linear"  # "linear" or "softmax"
