# configuration.yaml

data:
  pkl_name: './data_pkl.pkl'
  val_samples: ['02', '07']
  test_samples: ['08', '13', '15', '22', '28']

model:
  name: "LSTM1"
  num_layers: None
  seq_length_s: 3
  input_dim: 54
  hidden_dim1: 32
  hidden_dim2: 2
  #hidden_dim3: 0
  dropout_prob: 0.1

optimizer:
  name: "RMSprop"
  lr: 0.001
  lr_step_size: 5
  gamma: 0.2

training:
  batch_size: 16
  epochs: 30
  early_stop_patience: 5
  saved_dir: "./checkpoints"
  saved_best_model: "best_model2.pth"
